name: Build wheels
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_windows_wheel:
    name: Build wheel on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: apt-get update && apt-get install -y build-essential libx11-dev
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Build Windows wheel
        run: python setup.py bdist_wheel -d wheelhouse
      - name: Upload Windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: litecamera-windows-${{ matrix.python-version }}-wheels
          path: wheelhouse/*.whl
  build_linux_wheel:
    name: Build wheel on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Build Linux wheel
        run: python setup.py bdist_wheel -d wheelhouse
      - name: Upload Linux wheels
        uses: actions/upload-artifact@v4
        with:
          name: litecamera-linux-${{ matrix.python-version }}-wheels
          path: wheelhouse/*.whl
  build_macos_wheel:
    name: Build wheel on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Build macOS wheel
        run: python setup.py bdist_wheel -d wheelhouse
      - name: Upload macOS wheels
        uses: actions/upload-artifact@v4
        with:
          name: litecamera-macos-${{ matrix.python-version }}-wheels
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools
      - name: Build source distribution
        run: python setup.py sdist -d dist
      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: litecamera-source-distribution
          path: dist/*.tar.gz
